language: node_js
node_js:
  - "5.6"
addons:
  postgresql: "9.4"
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - PORT=9999 DATABASE_URL=postgresql://postgres@localhost/travis_ci_test CXX=g++-4.8

